# Generated by Django 5.2.17 on 2026-08-27 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='datos de contacto')),
                ('creada_por_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de alta')),
            ],
            options={
                'verbose_name': 'biblioteca',
                'verbose_name_plural': 'bibliotecas',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('es_central', models.BooleanField(default=False, verbose_name='es cuenta central')),
                ('nombre_visible', models.CharField(blank=True, max_length=120, verbose_name='nombre visible')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='cuentas.biblioteca')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ['-es_central', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='EntradaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo_operacion', models.CharField(max_length=60, verbose_name='tipo de operación')),
                ('entidad', models.CharField(choices=[('ejemplar', 'Ejemplar'), ('titulo', 'Título'), ('prestamo', 'Préstamo'), ('persona', 'Persona prestataria'), ('configuracion', 'Configuración'), ('operador', 'Operador')], max_length=20, verbose_name='entidad')),
                ('entidad_id', models.BigIntegerField(blank=True, null=True, verbose_name='id de la entidad')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('actor', models.ForeignKey(blank=True, help_text='Subcuenta autora; NULL solo para el proceso automático de anonimización.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to=settings.AUTH_USER_MODEL)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='cuentas.biblioteca')),
            ],
            options={
                'verbose_name': 'entrada de auditoría',
                'verbose_name_plural': 'auditoría',
                'ordering': ['-fecha_hora', '-id'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='cuentas_ent_entidad_296d86_idx'), models.Index(fields=['-fecha_hora'], name='cuentas_ent_fecha_h_d7488a_idx')],
            },
        ),
    ]
