# Generated by Django 5.2.17 on 2026-08-27 21:00

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_extensiones'),  # pg_trgm / unaccent para el índice GIN de búsqueda
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('autor', models.CharField(max_length=200, verbose_name='autor')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('isbn_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=20)),
                ('editorial', models.CharField(blank=True, max_length=200, verbose_name='editorial')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='año de publicación')),
                ('materia', models.CharField(blank=True, max_length=120, verbose_name='materia / categoría')),
                ('busqueda_norm', models.CharField(blank=True, editable=False, max_length=700)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='cuentas.biblioteca')),
            ],
            options={
                'verbose_name': 'título',
                'verbose_name_plural': 'títulos',
                'ordering': ['titulo', 'autor'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código de ejemplar')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('retirado', 'Retirado')], default='disponible', max_length=12, verbose_name='estado')),
                ('motivo_retirada', models.CharField(blank=True, max_length=200, verbose_name='motivo de retirada')),
                ('ubicacion', models.CharField(blank=True, max_length=120, verbose_name='ubicación / signatura')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='catalogo.titulo')),
            ],
            options={
                'verbose_name': 'ejemplar',
                'verbose_name_plural': 'ejemplares',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['busqueda_norm'], name='catalogo_titulo_busq_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ejemplar',
            index=models.Index(fields=['titulo', 'estado'], name='catalogo_ej_titulo__512dae_idx'),
        ),
    ]
