# Generated by Django 5.2.17 on 2026-08-27 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaPrestataria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('documento', models.CharField(blank=True, max_length=40, verbose_name='documento')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='nombre')),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='contacto')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('anonimizada', 'Anonimizada')], default='activa', max_length=12)),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='fecha de alta')),
                ('fecha_ultimo_prestamo', models.DateField(blank=True, null=True, verbose_name='fecha del último préstamo')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestatarios', to='cuentas.biblioteca')),
            ],
            options={
                'verbose_name': 'persona prestataria',
                'verbose_name_plural': 'personas prestatarias',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('persona_anonimizada', models.BooleanField(default=False)),
                ('fecha_prestamo', models.DateField(verbose_name='fecha de préstamo')),
                ('fecha_limite', models.DateField(verbose_name='fecha límite de devolución')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='fecha real de devolución')),
                ('dias_retraso', models.PositiveIntegerField(default=0, verbose_name='días de retraso')),
                ('estado_registro', models.CharField(choices=[('efectivo', 'Efectivo'), ('anulado', 'Anulado')], default='efectivo', max_length=10)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='cuentas.biblioteca')),
                ('devolucion_registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='prestamos.personaprestataria')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
                'ordering': ['-fecha_prestamo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GestionReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha', models.DateField()),
                ('medio', models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo electrónico'), ('presencial', 'Presencial'), ('otro', 'Otro')], max_length=12)),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'gestión de reclamación',
                'verbose_name_plural': 'gestiones de reclamación',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('anulacion', 'Anulación'), ('correccion', 'Corrección')], max_length=12)),
                ('operacion', models.CharField(choices=[('prestamo', 'Préstamo'), ('devolucion', 'Devolución'), ('retirada', 'Retirada')], max_length=12)),
                ('motivo', models.CharField(max_length=300)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='cuentas.biblioteca')),
                ('ejemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='catalogo.ejemplar')),
                ('realizada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'corrección de operación',
                'verbose_name_plural': 'correcciones de operación',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='personaprestataria',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('biblioteca', 'documento'), name='persona_documento_unico_activa'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['ejemplar', '-fecha_prestamo'], name='prestamos_p_ejempla_864726_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['persona'], name='prestamos_p_persona_781292_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(condition=models.Q(('estado_registro', 'efectivo'), ('fecha_devolucion_real__isnull', True)), fields=['fecha_limite'], name='prestamo_vencidos_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_registro', 'efectivo'), ('fecha_devolucion_real__isnull', True)), fields=('ejemplar',), name='un_prestamo_activo_por_ejemplar'),
        ),
    ]
