# Generated by Django 5.2.17 on 2026-08-27 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('plazo_dias', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='plazo de préstamo (días naturales)')),
                ('max_prestamos_persona', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='máximo de préstamos activos por persona')),
                ('biblioteca', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parametros_prestamo', to='cuentas.biblioteca')),
            ],
            options={
                'verbose_name': 'parámetros de préstamo',
                'verbose_name_plural': 'parámetros de préstamo',
            },
        ),
    ]
